---
# tasks file for python_install

- name: Upgrade all OS packages
  # noqa package-latest
  ansible.builtin.apt:
    name: '*'
    update_cache: true
    state: latest
  become: true

- name: Install required OS packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ debian_os_packages }}"
  become: true
