---
# tasks file for python

- name: RedHat | Upgrade all OS packages.
  # noqa package-latest
  ansible.builtin.dnf:
    name: '*'
    state: latest
  become: true

- name: RedHat | Install required OS packages.
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ python_os_packages }}"
  become: true
