---
# tasks file for python

- name: setup_redhat | Upgrade all OS packages.
  # noqa package-latest
  ansible.builtin.dnf:
    name: '*'
    state: latest
  become: true

- name: setup_redhat | Install required OS packages.
  ansible.builtin.dnf:
    name: "{{ python_item }}"
    state: present
  loop: "{{ python_os_packages }}"
  loop_control:
    loop_var: python_item
  become: true
