---
# tasks file for python

- name: setup_debian | Upgrade all OS packages.
  # noqa package-latest
  ansible.builtin.apt:
    name: '*'
    update_cache: true
    state: latest
  become: true

- name: setup_debian | Install required OS packages.
  ansible.builtin.apt:
    name: "{{ python_item }}"
    state: present
  loop: "{{ python_os_packages }}"
  loop_control:
    loop_var: python_item
  become: true
