---
# tasks file for python

- name: Setup_Debian | Upgrade all OS packages.
  # noqa package-latest
  ansible.builtin.apt:
    name: '*'
    update_cache: true
    state: latest
  become: true

- name: Setup_Debian | Install required OS packages.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ python_os_packages }}"
  become: true
