---
# handlers file for python

- name: Remove downloaded Python archive.
  ansible.builtin.file:
    path: "{{ python_download_dir }}/{{ python_archive }}"
    state: absent

- name: Remove extracted Python binaries.
  ansible.builtin.file:
    path: "{{ python_unarchive_dir }}"
    state: absent
